Repository BostonGosari/Baseline, pull requests merged in 2023-10, with the labels that each got.

#4 feature #2 : 로그인 기능 구현
  .gitignore
  Austin/Austin.xcodeproj/project.pbxproj
  Austin/Austin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Austin/Austin/Austin.entitlements
  Austin/Austin/AustinApp.swift
  Austin/Austin/Info.plist
  Austin/Austin/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Austin/Austin/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Austin/Austin/Resources/Assets.xcassets/Contents.json
  Austin/Austin/Resources/Assets.xcassets/kakao_login_large_wide.imageset/Contents.json
  Austin/Austin/Resources/Assets.xcassets/kakao_login_large_wide.imageset/kakao_login_large_wide.png
  Austin/Austin/Resources/Config.xcconfig
  Austin/Austin/Sources/AustinApp.swift
  Austin/Austin/Sources/ContentView.swift
  Austin/Austin/Sources/Login/View/LoginAppleButton.swift
  Austin/Austin/Sources/Login/View/LoginKakaoButton.swift
  Austin/Austin/Sources/Login/View/LoginView.swift
Labels: ✨ feature, 📁 data

#15 feature #14 : Carousel 뷰 구현
  Tyler/Tyler.xcodeproj/project.pbxproj
  Tyler/Tyler/Carousel/Carousel.swift
  Tyler/Tyler/Carousel/CarouselView.swift
  Tyler/Tyler/Carousel/CarouselView_iOS.swift
  Tyler/Tyler/ContentView.swift
Labels: ✨ feature, 🎨 design

#10 feature #5 : 사용자가 이동할 경로를 맵에 표시
  Tyler/Tyler.xcodeproj/project.pbxproj
  Tyler/Tyler/Assets.xcassets/duck.imageset/Contents.json
  Tyler/Tyler/Assets.xcassets/duck.imageset/duck.png
  Tyler/Tyler/Assets.xcassets/startpoint.imageset/Contents.json
  Tyler/Tyler/Assets.xcassets/startpoint.imageset/startpoint.png
  Tyler/Tyler/ContentView.swift
  Tyler/Tyler/Map/SwiftUI/MapView_iOS16.swift
  Tyler/Tyler/Map/SwiftUI/MapView_iOS17.swift
  Tyler/Tyler/Map/UIKit/KMLParser.swift
  Tyler/Tyler/Map/UIKit/MainView.swift
  Tyler/Tyler/Map/UIKit/MapAnimationView.swift
  Tyler/Tyler/Map/UIKit/MapUserView.swift
  Tyler/Tyler/Map/UIKit/MapView.swift
  Tyler/Tyler/Map/UIKit/duckRun.kml
Labels: ✨ feature, 🎨 design, 📁 data

#13 feature #12 : watchOS 와 iOS 사이의 데이터 송수신 기능 구현
  Tyler/Tyler.xcodeproj/project.pbxproj
  Tyler/Tyler/WatchConnectivity/DeviceCommunicator.swift
  Tyler/Tyler/WatchConnectivity/WatchConnectivityView.swift
  Tyler/WatchTyler Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  Tyler/WatchTyler Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  Tyler/WatchTyler Watch App/Assets.xcassets/Contents.json
  Tyler/WatchTyler Watch App/ContentView.swift
  Tyler/WatchTyler Watch App/Preview Content/Preview Assets.xcassets/Contents.json
  Tyler/WatchTyler Watch App/WatchConnectivity/WatchConnectivityView.swift
  Tyler/WatchTyler Watch App/WatchTylerApp.swift
Labels: ✨ feature, ⌚️ watch, 📁 data

#17 feature #16 : 화면 축하 애니메이션
  Tyler/Tyler.xcodeproj/project.pbxproj
  Tyler/Tyler/ScreenAnimation/Confetti/Confetti.swift
  Tyler/Tyler/ScreenAnimation/Confetti/Shapes.swift
  Tyler/Tyler/ScreenAnimation/ConfettiView.swift
Labels: ✨ feature, 🎨 design, ⌚️ watch
